// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnePieceMap.Infrastructure.Data;

#nullable disable

namespace OnePieceMap.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804214526_AddTranslationsColumns")]
    partial class AddTranslationsColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Arc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GlobalOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("SagaId")
                        .HasColumnType("integer");

                    b.Property<string>("Translations")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GlobalOrder")
                        .IsUnique();

                    b.HasIndex("SagaId", "Order")
                        .IsUnique();

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.ArcIsland", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArcId")
                        .HasColumnType("integer");

                    b.Property<int>("IslandId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IslandId");

                    b.HasIndex("ArcId", "IslandId")
                        .IsUnique();

                    b.HasIndex("ArcId", "Order")
                        .IsUnique();

                    b.ToTable("ArcIslands");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.CharacterVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArcId")
                        .HasColumnType("integer");

                    b.Property<long?>("Bounty")
                        .HasColumnType("bigint");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Epithet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Translations")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ArcId");

                    b.HasIndex("CharacterId", "ArcId")
                        .IsUnique();

                    b.ToTable("CharacterVersions");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArcIslandId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArcIslandId", "Order")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterVersionId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "CharacterVersionId");

                    b.HasIndex("CharacterVersionId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CoordinateX")
                        .HasColumnType("real");

                    b.Property<float>("CoordinateY")
                        .HasColumnType("real");

                    b.Property<float>("CoordinateZ")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RotationY")
                        .HasColumnType("real");

                    b.Property<float>("Scale")
                        .HasColumnType("real");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translations")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Islands");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Saga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Translations")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Sagas");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Arc", b =>
                {
                    b.HasOne("OnePieceMap.Domain.Entities.Saga", "Saga")
                        .WithMany("Arcs")
                        .HasForeignKey("SagaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Saga");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.ArcIsland", b =>
                {
                    b.HasOne("OnePieceMap.Domain.Entities.Arc", "Arc")
                        .WithMany("ArcIslands")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnePieceMap.Domain.Entities.Island", "Island")
                        .WithMany("ArcIslands")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Island");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.CharacterVersion", b =>
                {
                    b.HasOne("OnePieceMap.Domain.Entities.Arc", "Arc")
                        .WithMany("CharacterVersions")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnePieceMap.Domain.Entities.Character", "Character")
                        .WithMany("Versions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Event", b =>
                {
                    b.HasOne("OnePieceMap.Domain.Entities.ArcIsland", "ArcIsland")
                        .WithMany("Events")
                        .HasForeignKey("ArcIslandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArcIsland");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("OnePieceMap.Domain.Entities.CharacterVersion", "CharacterVersion")
                        .WithMany("Participations")
                        .HasForeignKey("CharacterVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnePieceMap.Domain.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterVersion");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Arc", b =>
                {
                    b.Navigation("ArcIslands");

                    b.Navigation("CharacterVersions");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.ArcIsland", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Character", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.CharacterVersion", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Island", b =>
                {
                    b.Navigation("ArcIslands");
                });

            modelBuilder.Entity("OnePieceMap.Domain.Entities.Saga", b =>
                {
                    b.Navigation("Arcs");
                });
#pragma warning restore 612, 618
        }
    }
}
