using OnePieceMap.Domain.Entities;
using OnePieceMap.Domain.Enums;

namespace OnePieceMap.Infrastructure.Seed;

// Shapes for Seed/characters.json and Seed/factions.json — global rosters, loaded once,
// referenced by every saga file. Recurring content (a character or faction that shows up
// across many sagas) lives here exactly once instead of duplicating per file.
internal record SeedCharacterRoster(List<SeedCharacter> Characters);

internal record SeedFactionRoster(List<SeedFaction> Factions);

// Shape of each Seed/sagas/<name>.json file — one saga's worth of content. "Id" fields
// are local correlation keys used only while seeding (unique within THIS file, not
// globally) — the real primary keys are generated by the database on insert. Everything
// here except CharacterId/FactionId references is intra-file: an Arc's CharacterVersion,
// an Island's ArcIsland, an Event's ArcIsland — all live in the same saga they belong to.
internal record SeedSagaFile(
    SeedSaga Saga,
    List<SeedArc> Arcs,
    List<SeedIsland> Islands,
    List<SeedArcIsland> ArcIslands,
    List<SeedCharacterVersion> CharacterVersions,
    List<SeedEvent> Events,
    List<SeedEventParticipant> EventParticipants);

internal record SeedSaga(int Id, string Name, int Order, Dictionary<string, SagaTranslation>? Translations = null);

// No SagaId: exactly one saga per file, so the arc's saga is always "this file's saga" —
// carrying a redundant reference would only be one more way for the data to disagree with itself.
internal record SeedArc(int Id, string Name, int Order, int GlobalOrder, Dictionary<string, ArcTranslation>? Translations = null);

internal record SeedIsland(
    int Id, string Name, string Slug, string Description,
    float CoordinateX, float CoordinateY, float CoordinateZ,
    float RotationY, float Scale, string ModelUrl, string ThumbnailUrl, bool IsActive,
    Dictionary<string, IslandTranslation>? Translations = null);

internal record SeedArcIsland(int Id, int ArcId, int IslandId, int Order);

internal record SeedCharacter(int Id, string Name, string Slug);

internal record SeedFaction(
    int Id, string Name, string Slug, Dictionary<string, FactionTranslation>? Translations = null);

// CharacterId/FactionId reference the global rosters (characters.json/factions.json);
// ArcId references an arc within this same file.
internal record SeedCharacterVersion(
    int Id, int CharacterId, int ArcId, string Alias, string Epithet,
    long? Bounty, CharacterStatus Status, int FactionId, string ImageUrl, string Description,
    Dictionary<string, CharacterVersionTranslation>? Translations = null);

internal record SeedEvent(
    int Id, int ArcIslandId, string Title, string Description, EventType Type, int Order,
    Dictionary<string, EventTranslation>? Translations = null);

internal record SeedEventParticipant(int EventId, int CharacterVersionId);
